---
apiVersion: v1
kind: ConfigMap
metadata:
  name: curl-test
data:
  index.html: |
    <html>
      <head>
        <title>Die Bart</title>
      </head>
      <body>
        <h1>Die Bart</h1>
        <h2>DIIIIIEEEE</h2>
        <img src="https://josheck.files.wordpress.com/2013/07/diebartdie.jpg" alt="die bart die">
      </body>
    </html>
...
---
apiVersion: v1
kind: Service
metadata:
  name: curl-test
spec:
  selector:
    app: curl-test
  ports:
  - port: 80
    targetPort: 80
...
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: curl-test
  labels:
    app: curl-test
spec:
  rules:
  - host: test.local
    http:
      paths:
      - backend:
          serviceName: curl-test
          servicePort: 80
...
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  labels:
    app: curl-test
spec:
  volumes:
    - name: resources
      configMap:
          name: curl-test
  containers:
  - name: tester
    image: nginx
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: resources
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
...